dev
Anvean21/KovalenkoEvgeniy-EducationPortal pull request #3
Opened 2021-05-11 17:20 UTC by Anvean21

2021-05-19 09:42 UTC, DaniilManita commented on EducationPortal/EducationPortal.Domain.Core/BookMaterial.cs
> +
буду бить по рукам

2021-05-19 09:43 UTC, DaniilManita commented on EducationPortal/EducationPortal.Domain.Core/BookMaterial.cs
> +   public class BookMaterial:Material
Ctrl + k + d

2021-05-19 09:45 UTC, DaniilManita commented on EducationPortal/EducationPortal.Domain.Core/BookFormat.cs
> +namespace EducationPortal.Domain.Core
может мейк сенс сделать папочку ентити и сложить туда все сущности, в зависимости от их количества и специализации, разбить еще на доп папочки... и на уровне с папкой ентити, сделать папочку с енамками ?

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal.Domain.Interfaces/IRepository.cs
> +        T Get(int id);
я не понимаю что значит Get, может GetById?

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal.Infrastructure.Data/Hasher/PasswordHasher.cs
> +namespace EducationPortal.Infrastructure.Data.Hesher
hEsher???

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal.Services.Interfaces/IUserService.cs
> +        public IEnumerable<User> UsersList();
для чего тебе нужен список всех пользователей, что ты с ним делать будешь ?

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal/FluentValidationModels/ArticleMaterialValidator.cs
> +            RuleFor(x => x.Passed).NotNull();
почему только на нул проверка ?

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal/FluentValidationModels/CourseValidator.cs
> +            RuleFor(x => x.Description).NotEmpty().MinimumLength(20).WithMessage("Invalid description. min 20 symbols");
в таком случае не рекваед выводить кастом месседж, у тебя и так он из под коробки будет вполне валидный

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal/FluentValidationModels/UserValidator.cs
> +            Regex reg = new Regex(@"^(?("")(""[^""]+?""@)|(([0-9a-z]((\.(?!\.))|[-!#\$%&'\*\+/=\?\^`\{\}\|~\w])*)(?<=[0-9a-z])@))" + @"(?(\[)(\[(\d{1,3}\.){3}\d{1,3}\])|(([0-9a-z][-\w]*[0-9a-z]*\.)+[
есть валидация у флюента для имейла из под коробки

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal/Helpers/Map.cs
> +    }
зачем ты это в хелперы засунул ? ты можешь это заинжектить в стартапе к примеру, потом через конструктор прокинуть свой маппер, либо же в конструкторе инжектить только необходимый тебе маппер, или же сделать что то типа фактори, и так же через конструктор все это делать, это не относится к твоему хелперу ну вот вообще никак

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal/Program.cs
> +            }
можно использовать например паттерн команду

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal/ViewModels/ArticleMaterialVM.cs
> +   public class ArticleMaterialVM:MaterialVM
форматииииироооваааниее

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal/ViewModels/SkillVM.cs
> +        [Required]
зачем оно тебе ? ты ж юзаешь флюент ?

2021-05-19 09:56 UTC, DaniilManita commented on EducationPortal/EducationPortal/ViewModels/UserVM.cs
> +
глазам больно

2021-05-19 14:56 UTC, Anvean21 commented on EducationPortal/EducationPortal/Helpers/Map.cs
> +    }
> зачем ты это в хелперы засунул ? ты можешь это заинжектить в стартапе к примеру, потом через конструктор прокинуть свой маппер, либо же в конструкторе инжектить только необходимый тебе маппер, или же сделать что то типа фактори, и так же через конструктор все это делать, это не относится к твоему хелперу ну вот вообще никак

Для этого как я понимаю нужно сделать интерфейс маппера? И добавить некий новый слой абстракции в виде каких-то контроллеров в UI, и там инжектить/мапить, верно?

2021-05-19 15:18 UTC, DaniilManita commented on EducationPortal/EducationPortal/Helpers/Map.cs
> +    }
нет, там уже все реализованно, тебе просто нужно выбрать способ как ты хочешь его заинжектить, погугли, почитай как это делается

2021-05-21 08:09 UTC, DaniilManita commented on EducationPortal/EducationPortal.Infrastructure.Data/JsonRepository.cs
> +    public class JsonRepository<T> : IRepository<T> where T : class
то есть я могу прокинуть любой класс ? DbContext например. интересно ))0

2021-05-21 08:09 UTC, DaniilManita commented on EducationPortal/EducationPortal/Creator/CourseCreator.cs
> +    public static class CourseCreator
а почему он у тебя статический ?

2021-05-23 11:28 UTC, vladimir-shirmanov requested changes
Нормально. Исправляй комментарии, и в другой раз ветки именую более логично это во первых и во вторых не надо все через одну ветку заливать. Отдельная фича - отдельная ветка. это мержи

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal.Domain.Core/Entities/Materials/VideoMaterial.cs
> +        public string Duration { get; set; }
А почему строка?

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal.Domain.Core/Entities/User.cs
> +        public ICollection<Skill> Skills { get; set; }
а чем это отличается от ExistingUserSkills этого

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal.Infrastructure.Business/EducationPortal.Infrastructure.Business.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
А зачем это? почему у тебя реализация бизнес логики лежит на уровне инфраструктуры? Бизнес логика это ядро системы, оно находится в Application/Core слое

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal.Infrastructure.Business/MaterialService.cs
> +        private IRepository<BookMaterial> bookMaterialRepository;
А если будет еще 20 типов материалов, во что этот класс превратится

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal.Infrastructure.Business/SkillService.cs
> +            return skillRepository.GetAll().FirstOrDefault(x => x.Name.ToLower() == name.ToLower());
То есть ты вытягиваешь из БД все скилы которые там есть и потом в памяти их фильтруешь?

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal.Infrastructure.Business/UserService.cs
> +            var userFromDb = userRepository.GetAll().FirstOrDefault(x => x.Email.ToLower() == email.ToLower() && x.Password == password);
тоже самое, почему ты вытягиваешь все существующие записи. Если их будет 10 миллионов, то твое приложение просто не будет работать

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal.Infrastructure.Business/UserService.cs
> +        public bool LogIn(string email, string password)
Пароль нельзя хранить в открытом виде

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal.Infrastructure.Data/Hasher/PasswordHasher.cs
> +            return Convert.ToBase64String(Encoding.UTF8.GetBytes(decodedPassword));
base64 это не хэш

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal.Services.Interfaces/IMaterialService.cs
> +        public void AddVideoMaterial(VideoMaterial videoMaterial);
Мне кажется тут нарушен Single responsibility principle

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/Creator/CourseCreator.cs
> +        private static readonly ICourseService courseService = CustomServiceProvider.Provider.GetRequiredService<ICourseService>();
А почему не использовать внедрение зависимости через конструктор?

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/Creator/CourseCreator.cs
> +        public static void CourseCreate()
а зачем тут статик?

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/FluentValidationModels/BookMaterialValidator.cs
> +            RuleFor(x => x.YearOfPublish).NotEmpty().Must(x => x <= DateTime.Today.Year);
А если книга в этом году вышла?

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/Helpers/UserHelper.cs
> +        public static (string, string) UserLoginData()
зачем тут tuple? еще и не именованный. Вот как понять незнакомому деву который будет юзать этот метод где тут логин а где пароль?

2021-05-23 11:28 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/ServicesConfiguration/DependencyInjection.cs
> +            var provider = new ServiceCollection().AddSingleton(typeof(IRepository<>), typeof(JsonRepository<>))
почему репоз синглтон?

2021-05-23 11:58 UTC, Anvean21 commented on EducationPortal/EducationPortal/FluentValidationModels/BookMaterialValidator.cs
> +            RuleFor(x => x.YearOfPublish).NotEmpty().Must(x => x <= DateTime.Today.Year);
> А если книга в этом году вышла?

Там ведь "меньше или равно"..

2021-05-23 12:02 UTC, Anvean21 commented on EducationPortal/EducationPortal/Creator/CourseCreator.cs
> +        private static readonly ICourseService courseService = CustomServiceProvider.Provider.GetRequiredService<ICourseService>();
> А почему не использовать внедрение зависимости через конструктор?

Мне со статиками удобнее работать, не нужно создавать экземпляр для вызова методов. Это критично?

2021-05-23 12:03 UTC, Anvean21 commented on EducationPortal/EducationPortal.Infrastructure.Business/UserService.cs
> +        public bool LogIn(string email, string password)
> Пароль нельзя хранить в открытом виде

В БД хранится зашифрованный

2021-05-23 12:03 UTC, Anvean21 commented on EducationPortal/EducationPortal.Infrastructure.Business/UserService.cs
> +            var userFromDb = userRepository.GetAll().FirstOrDefault(x => x.Email.ToLower() == email.ToLower() && x.Password == password);
> тоже самое, почему ты вытягиваешь все существующие записи. Если их будет 10 миллионов, то твое приложение просто не будет работать
Изменение в репозитории метода GetAll c IEnumerable на IQueryble решит проблему насколько я понимаю?

2021-05-23 12:04 UTC, Anvean21 commented on EducationPortal/EducationPortal.Infrastructure.Business/EducationPortal.Infrastructure.Business.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
> А зачем это? почему у тебя реализация бизнес логики лежит на уровне инфраструктуры? Бизнес логика это ядро системы, оно находится в Application/Core слое

Логически так и есть, просто оно в папке под названием Infrastructure

2021-05-23 12:09 UTC, Anvean21 commented on EducationPortal/EducationPortal.Domain.Core/Entities/Materials/VideoMaterial.cs
> +        public string Duration { get; set; }
> А почему строка?

feature

2021-05-23 13:16 UTC, Anvean21 commented on EducationPortal/EducationPortal.Infrastructure.Business/MaterialService.cs
> +        private IRepository<BookMaterial> bookMaterialRepository;
> А если будет еще 20 типов материалов, во что этот класс превратится

В глобальный рефакторинг, пока это вынужденная мера для корректной сериализации, и сохранения материалов по разным папкам

2021-05-23 13:20 UTC, Anvean21 commented on EducationPortal/EducationPortal/Creator/CourseCreator.cs
> +        private static readonly ICourseService courseService = CustomServiceProvider.Provider.GetRequiredService<ICourseService>();
> > А почему не использовать внедрение зависимости через конструктор?
> 
> Мне со статиками удобнее работать, не нужно создавать экземпляр для вызова методов. Это критично?
+ Меньше кода, ненужно создавать экземпляры классов, и тд.
Единственный "минус" это статические методы, не знаю насколько это плохо в данном случае.

2021-05-23 15:11 UTC, merged